-- Generated from content.js. Seeds D1 with the current site content.
-- Regenerate with: python3 tools/seed-from-content.py

DELETE FROM postcards; DELETE FROM projects; DELETE FROM seasons; DELETE FROM site;

INSERT INTO site (key, value) VALUES ('email', 'yarenkecici022@gmail.com');
INSERT INTO site (key, value) VALUES ('emailSubject', 'A place worth remembering');
INSERT INTO site (key, value) VALUES ('instagram', 'https://www.instagram.com/saucerfulsecrets/');
INSERT INTO site (key, value) VALUES ('credit', 'By Atlasophy');

INSERT INTO seasons (id, label, film, note, position) VALUES ('spring', 'Spring', 'Portra 400', 'Soft light, new rituals, open windows.', 0);
INSERT INTO seasons (id, label, film, note, position) VALUES ('summer', 'Summer', 'Ektachrome E100', 'Salt air, long tables, sun-warmed walls.', 1);
INSERT INTO seasons (id, label, film, note, position) VALUES ('autumn', 'Autumn', 'Kodak Gold 200', 'Earthy rooms, slower days, stories by the fire.', 2);
INSERT INTO seasons (id, label, film, note, position) VALUES ('winter', 'Winter', 'Ilford HP5', 'Crisp air, warm windows, quiet between places.', 3);

INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('spring', 'the-sunday-table', 'The Sunday Table', 'Stay', 'Slovenia', 'Slovenia countryside guesthouse', 'assets/stories/spring-1.webp', 'A morning shaped by open windows, handmade ceramics, and nowhere else to be.', 'The house wakes slowly. Light moves across the table, coffee cools beside a vase of new branches, and breakfast becomes the first small ceremony of the day.', 0);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('spring', 'cabin-in-bloom', 'Cabin in Bloom', 'Retreat', 'Austria', 'Austrian Alps cabin', 'assets/stories/spring-2.webp', 'A dark timber hideaway held quietly beneath the first blossoms of the year.', 'At the edge of the orchard, the little cabin feels separate from time. The story is in the contrast: blackened wood, pale petals, and grass returning after winter.', 1);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('spring', 'hands-in-clay', 'Hands in Clay', 'Maker', 'Provence', 'Provence France pottery studio', 'assets/stories/spring-3.webp', 'An afternoon among earth, quiet shelves, and objects made to be kept.', 'The studio speaks through traces—clay dust on the table, imperfect rims, tools left where the work paused. We photographed the process through its atmosphere rather than a pose.', 2);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('spring', 'after-the-rain', 'After the Rain', 'Café', 'Annecy', 'Annecy France old town', 'assets/stories/spring-4.webp', 'Wet cobblestones, green awnings, and the first table set back outside.', 'Rain changes a familiar street. Colors deepen, bicycles shine, and a neighborhood café becomes a small pool of warmth at the corner.', 3);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('spring', 'room-to-breathe', 'Room to Breathe', 'Stay', 'Lake Como', 'Lake Como Italy', 'assets/stories/spring-5.webp', 'A room designed around morning light and the pleasure of doing less.', 'Nothing here asks for attention. Linen, limewash, a single branch, and the soft movement of a curtain are enough to make the room memorable.', 4);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('summer', 'aegean-blue', 'Aegean Blue', 'Travel', 'Greece', 'Cyclades Greece', 'assets/stories/summer-1.webp', 'A coastal study in limestone, pine shade, and impossible blue.', 'The cove reveals itself between branches and stone. We followed the changing color of the water and the instinctive paths that lead down to it.', 0);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('summer', 'casa-serena', 'Casa Serena', 'Stay', 'Puglia', 'Puglia Italy', 'assets/stories/summer-2.webp', 'White geometry, olive shade, and a pool holding the midday sky.', 'Casa Serena is about restraint. Its strongest details are the oldest ones: lime, local stone, an olive tree, and the movement of light across water.', 1);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('summer', 'the-tomato-summer', 'The Tomato Summer', 'Kitchen', 'Mallorca', 'Mallorca Spain', 'assets/stories/summer-3.webp', 'A kitchen story told through sun, ripe produce, and the generosity of a shared table.', 'The counter becomes a palette of reds and greens. Nothing is styled beyond the natural rhythm of ingredients gathered for lunch.', 2);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('summer', 'harbour-hours', 'Harbour Hours', 'Local story', 'Sicily', 'Sicily Italy fishing harbour', 'assets/stories/summer-4.webp', 'Weathered paint and salt-marked timber in a harbor that still works for a living.', 'The old boat carries its history on the surface. Scratches, knots, and faded color tell more than a perfect finish ever could.', 3);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('summer', 'under-the-olives', 'Under the Olives', 'Table', 'Menorca', 'Menorca Spain', 'assets/stories/summer-5.webp', 'The suspended moment before guests arrive and the long dinner begins.', 'Blue hour settles over the table as candles are lit one by one. The images hold that brief anticipation before voices fill the garden.', 4);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('autumn', 'into-the-woods', 'Into the Woods', 'Cabin', 'Dolomites', 'Dolomites Italy cabin', 'assets/stories/autumn-1.webp', 'A black cabin, copper leaves, and mist moving through the trees.', 'The weather made the story. Low cloud softened the forest while the cabin windows offered the only warm note in the landscape.', 0);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('autumn', 'the-reading-room', 'The Reading Room', 'Hotel', 'Edinburgh', 'Edinburgh Scotland', 'assets/stories/autumn-2.webp', 'A room made for rain, old books, and one more hour in the chair.', 'Deep green velvet and dark timber give this corner its gravity. We photographed the room as an invitation to stay rather than a catalogue of things.', 1);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('autumn', 'harvest-walk', 'Harvest Walk', 'Vineyard', 'Tuscany', 'Tuscany Italy vineyard', 'assets/stories/autumn-3.webp', 'Rows of gold leading toward a farmhouse at the end of the season.', 'Autumn gives the vineyard structure and softness at once. The geometry of the rows carries the eye into hills washed with late-afternoon haze.', 2);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('autumn', 'daily-bread', 'Daily Bread', 'Bakery', 'Salzburg', 'Salzburg Austria bakery', 'assets/stories/autumn-4.webp', 'Flour, dark crust, and the warm window of a neighborhood ritual.', 'The bakery is most beautiful before the street is fully awake. Fresh loaves gather in the window while warm light meets the cool morning outside.', 3);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('autumn', 'window-seat', 'Window Seat', 'Travel', 'Switzerland', 'Swiss Alps scenic train', 'assets/stories/autumn-5.webp', 'Rain on glass and a mountain town arriving slowly into view.', 'Travel is sometimes best photographed from the seat. The water on the window turns the town into a memory before we have even reached it.', 4);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('winter', 'first-snow', 'First Snow', 'Chalet', 'Chamonix', 'Chamonix France chalet', 'assets/stories/winter-1.webp', 'A chalet glowing at blue hour beneath the first deep snow.', 'Warm windows become landmarks in winter. We arrived as daylight faded and photographed the chalet as shelter against the scale of the mountain.', 0);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('winter', 'northern-light', 'Northern Light', 'Stay', 'Norway', 'Norway fjord guesthouse', 'assets/stories/winter-2.webp', 'Pale timber, white linen, and a room borrowing its color from the snow.', 'The guesthouse uses very little, and every material matters. Winter light moves gently through the space, revealing grain, weave, and quiet.', 1);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('winter', 'still-water', 'Still Water', 'Retreat', 'Iceland', 'Iceland geothermal pool', 'assets/stories/winter-3.webp', 'Steam rising between black rock and dark pines in complete silence.', 'The pool appears almost unreal, but its beauty is elemental: heat, water, stone, and cold air. We kept the frame empty so the place could breathe.', 2);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('winter', 'the-roastery', 'The Roastery', 'Café', 'Copenhagen', 'Copenhagen Denmark coffee roastery', 'assets/stories/winter-4.webp', 'Brass machinery and warm cups at the heart of an independent café.', 'The roaster is both tool and sculpture. Its warm metal gives the small room a glow that carries through every frame.', 3);
INSERT INTO projects (season_id, slug, title, type, place, location, image, deck, story, position) VALUES ('winter', 'a-quiet-passage', 'A Quiet Passage', 'Travel', 'Kraków', 'Krakow Poland old town', 'assets/stories/winter-5.webp', 'An old stone lane before footsteps mark the new snow.', 'Early winter mornings offer a city back to itself. Without crowds, the curve of the street and the repetition of windows become the whole story.', 4);

INSERT INTO postcards (image, meta, title, season_id, story_slug, position) VALUES ('assets/stories/summer-5.webp', 'Menorca · After midnight', 'The table they set after everyone else had gone home', 'summer', 'under-the-olives', 0);
INSERT INTO postcards (image, meta, title, season_id, story_slug, position) VALUES ('assets/stories/autumn-5.webp', 'Tatras · Night train', 'Waking up at the last station before the mountains', 'autumn', 'window-seat', 1);
INSERT INTO postcards (image, meta, title, season_id, story_slug, position) VALUES ('assets/stories/autumn-4.webp', 'Salzburg · 05:12', 'Inside the bakery before the first tram passed', 'autumn', 'daily-bread', 2);
INSERT INTO postcards (image, meta, title, season_id, story_slug, position) VALUES ('assets/stories/winter-3.webp', 'Iceland · Below zero', 'A winter bath where the road quietly disappears', 'winter', 'still-water', 3);
INSERT INTO postcards (image, meta, title, season_id, story_slug, position) VALUES ('assets/stories/spring-3.webp', 'Provence · Wild clay', 'Learning why this village never paints its pottery', 'spring', 'hands-in-clay', 4);
INSERT INTO postcards (image, meta, title, season_id, story_slug, position) VALUES ('assets/stories/spring-2.webp', 'Austria · No road in', 'Three days in the orchard cabin reached only on foot', 'spring', 'cabin-in-bloom', 5);
